// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQckAF5FYizUwRD9g6ocCfQbIh6LAFRoA',
    appId: '1:213879262956:web:11f4b9547b8f245a045fc9',
    messagingSenderId: '213879262956',
    projectId: 'eva-pro-2025',
    authDomain: 'eva-pro-2025.firebaseapp.com',
    storageBucket: 'eva-pro-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2DQcOzcWGhfbnI4O0OUgVjTqhZPO8wAk',
    appId: '1:213879262956:android:cde6450ffcdd2f64045fc9',
    messagingSenderId: '213879262956',
    projectId: 'eva-pro-2025',
    storageBucket: 'eva-pro-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdcD9icr29LZrsiKMYkkqWOznfLNrssqM',
    appId: '1:213879262956:ios:9f5239c5f608eb12045fc9',
    messagingSenderId: '213879262956',
    projectId: 'eva-pro-2025',
    storageBucket: 'eva-pro-2025.firebasestorage.app',
    iosBundleId: 'com.example.evapro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQckAF5FYizUwRD9g6ocCfQbIh6LAFRoA',
    appId: '1:213879262956:web:bcee2c4880a562e1045fc9',
    messagingSenderId: '213879262956',
    projectId: 'eva-pro-2025',
    authDomain: 'eva-pro-2025.firebaseapp.com',
    storageBucket: 'eva-pro-2025.firebasestorage.app',
  );
}
